### ISSUE TITLE
Whitepaper is incomplete?

### ISSUE THREAD

**Issue by stv0g** [rosenpass/rosenpass#68]
I've started to work on a Golang implementation of the Rosenpass key exchange [1].
While implementing it, I stumbled over some confusing parts in the whitepaper:

### Variables / message fields `mac`, `cookie`, `ini_enc` & `res_enc`

Figure 3 shows the output variables `mac` and `cookie` which apparently should be included in a message envelope (Figure 2).
But I find no mention about use of the `mac` and `cookie` variable elsewhere in the whitepaper.

Apart from the `osk` two more output variables are generated after the completion of the handshake: `ini_enc` & `res_enc`
What is their purpose?

### Message types: Data & CookieReply

Figure 2 shows these two message types. But they are nowhere described or used?

### Live session state

Section 2.4.4 covers some variables which are not described and used in the handshake?

- txkm – Our transmission key
- txnm – Our transmission nonce
- sidt – Peer’s session ID (“theirs”)
- txkt – Peer’s transmission key
- txnt – Peer’s transmission nonce

### Enter live helper

What is the purpose of the `enter_live` helper function mentioned in section 2.5?
It appears also not to be used?

[1] https://github.com/stv0g/go-rosenpass

**Comment by koraa** [comment]
The root cause of most of these issues is assuming knowledge of the WireGuard whitepaper[^0]. This is an oversight; if we assume the reader knows the WireGuard whitepaper, we should say so and we shouldn't require users to read the WG whitepaper in the first place.

The other thing to know is that Rosenpass is structured like WireGuard -- it is designed to act like a VPN protocol but in practice we just use it to send a key to WireGuard; this leads to some oddities like the present but barely-used live transport data feature.

- `mac`, `cookie` -- Message integrity checking and proof-of-ip-ownership. See the WireGuard whitepaper section 5.4.4; Rosenpass whitepaper[^1] figure 3 and [Envelope::seal](https://github.com/rosenpass/rosenpass/blob/3856d774ff6c6954a3157d322d9846637d635c6a/src/protocol.rs#L1159) in the code. Rosenpass currently does not implement the proof-of-ip-ownership mechanism and always leaves the cookie-field empty
- `ini_enc`, `res_enc` -- These should be called `txki` and `txkr` (transmission key receiver/responder), which is another oversight. They are used to send transport data. The rosenpass application just outputs a key so there is no payload; these are still used to abort retransmissions in case of packages loss.
- Data & CookieReply -- These would be used if we implemented payload transmission and proof-of-ip-ownership. Leaving them orphaned like this was a bad practice.

> Section 2.4.4 covers some variables which are not described and used in the handshake?

That actually was a deliberate decision. These variables are implied by the naming scheme; maybe we should make it more obvious that they are defined but unused.

> What is the purpose of the enter_live helper function mentioned in section 2.5?
It appears also not to be used?

On the contrary; it is used to enter the live transport session; Rosenpass does not implement live transport sessions but this is still needed to send the `EmptyData` packet that terminates the initiators attempts to retransmit the InitConf package in case of package loss.

See Rosenpass Whitepaper Fig. 4 instructions ICI7 and ICR7.

> How are the roles of initiator / responder assigned?

They are not assigned; both peers can be initiator and responder at the same time; such a situation results in two handshakes being executed at the same time. This is actually necessary to avoid denial of service attacks on the protocol level since without having executed the handshake neither party can be sure the other is legitimate. This is tricky to get right; the current rust implementation has a [race condition](https://github.com/rosenpass/rosenpass/issues/43) due to this; I need to spend some time figuring out how to fix this.

[^0]: https://www.wireguard.com/papers/wireguard.pdf
[^1]: https://rosenpass.eu/whitepaper.pdf

**Comment by stv0g** [comment]
Hi @koraa, and @Mullana 

thanks for the very detailed explanations 😃

I've seen that you already updated the figures of the whitepaper. I have two questions about the changes in Figure 2:

- Was the removal of the PRF label `biscuit_ad` intended?
- Also the PRF label `mix` has been removed for the hashing of `sidr` / `sidi` in the beginning of RespHello / InitConf phases.

Thanks a lot :)

**Comment by stv0g** [comment]
> ini_enc, res_enc -- These should be called txki and txkr (transmission key receiver/responder), which is another oversight. They are used to send transport data. The rosenpass application just outputs a key so there is no payload; these are still used to abort retransmissions in case of packages loss.

Should we maybe rename those as well in the figure?

**Comment by Mullana** [comment]
>     Was the removal of the PRF label biscuit_ad intended?
>     Also the PRF label mix has been removed for the hashing of sidr / sidi in the beginning of RespHello / InitConf phases.


Hi @stv0g 
That was my mistake. I accidentally used an old version. But it's already fixed!

**Comment by stv0g** [comment]
Oh you are right. Sorry, I was confused by GitHubs image-diffing feature..

**Comment by koraa** [comment]
> > ini_enc, res_enc -- These should be called txki and txkr (transmission key receiver/responder), which is another oversight.
> 
> Should we maybe rename those as well in the figure?

I think we should!

@Mullana Its not urgent at all :)

**Comment by stv0g** [comment]
Hi @koraa,

I added a little status section to the description of this ticket so we can track the progress.

There is another think, which should probably be added to the whitepaper:

### Endianess of biscuit counter

It is currently not defined but is essential for a working implementation.
Unfortunately, I am lacking the Rust skills to figure out myself the endianess.

**Comment by koraa** [comment]
@stv0g Thank you!

Everything is currently in little endian. And wonderful idea to add the counter.

**Comment by stv0g** [comment]
### Wrong cipher-text variable in Figure 4

In Figure 4, Step IHR5 it should probably say `decaps_and_mix<SKEM>(sskr, spkr, sctr)` instead of `decaps_and_mix<SKEM>(sskr, spkr, ct1)`

**Comment by stv0g** [comment]
@koraa Sorry for all the spam here. These are just peer-review comments about the whitepaper. Nothing critical or urgent. I just want to keep track of my comments so we can improve the next version of the white paper 😃 

### Better naming for session/index table

Section 2.4.1 mentions a global table for keeping track of ongoing session:

> `index` – A lookup table mapping the session ID to the ongoing initiator handshake
or live session

I am wondering where this naming comes from. I think something like `sessions` would be more appropriate here.

**Comment by koraa** [comment]
They are not spam; in fact, thanks a bunch for these comments. They are the sort of thing you only spot when you read a text really closely!
We will definetly address those comments; I think I'd prefer collecting the sum of them and then just applying the corrections en-block.

Thanks a bunch for your hard work! :1st_place_medal: :1st_place_medal: :1st_place_medal:

**Comment by stv0g** [comment]
### Inverted assertions for replay detection

The pseudo code for `load_biscuit()` includes the following assert statement:

```rust
assert(pt.biscuit_no ≤ peer.biscuit_used);
```

Shouldnt it be the opposite? E.g.:

```rust
assert(pt.biscuit_no > peer.biscuit_used);
```

The number in the biscuit must be larger than any previously seen number.

**Comment by stv0g** [comment]
### Wrong PRF labels for session encryption keys

The whitepaper uses the following PRF labels for deriving the session encryption keys:

- `ini_enc`: `initiator session encryption`
- `res_enc`: `responder session encryption`

However, the Rust implementation uses:

- `ini_enc`: `initiator handshake encryption`
- `res_enc`: `responder handshake encryption`

See: https://github.com/rosenpass/rosenpass/blob/b29720b0c67ddf96f114c134bed076f27018313e/src/labeled_prf.rs#L43

**Comment by stv0g** [comment]
### Section 2.3: Wrong protocol identifier in whitepaper

The whitepaper uses the following string as the protocol identifier

```
PROTOCOL = "rosenpass 1 rosenpass.eu aead=chachapoly1305 hash=blake2s
↪ ekem=kyber512 skem=mceliece460896 xaead=xchachapoly1305"
````

However, the Rust implementation uses:

https://github.com/rosenpass/rosenpass/blob/b29720b0c67ddf96f114c134bed076f27018313e/src/labeled_prf.rs#L10

**Comment by stv0g** [comment]
> Sheeesh, these are sizable errors :w

Ah, no problem. I am happy that I can give something back to the project with my Go implementation.
Even if a port to another language might not be really required, its probably a good way to find issues/inconsistencies :-)

**Comment by stv0g** [comment]
### Section 2.1.1: Wrong hash function?

Section 2.1.1 says:

> As keyed hash function we use the HMAC construction [12] with BLAKE2s [14] as the inner hash function.

However the Rust implementation used BLAKE2b:

https://github.com/rosenpass/rosenpass/blob/b29720b0c67ddf96f114c134bed076f27018313e/src/sodium.rs#L218

**Comment by stv0g** [comment]
### Section 2.1.1: Describe non-standard HMAC-Blake2 variant

I fallen into the trap to assume that the key of the inner Blake2 hash-function for the HMAC calculation will be set to zero like Wireguard is doing it:

https://github.com/WireGuard/wireguard-go/blob/052af4a8072bbbd3bfe7edf46fe3c1b350f71f08/device/noise-helpers.go#L24-L31

However, Rosenpass seems to take another approach and uses the `ipad`/`opad` xor-ed key (`temp_key` in the code) as the key for the inner hash functions:

https://github.com/rosenpass/rosenpass/blob/b29720b0c67ddf96f114c134bed076f27018313e/src/sodium.rs#L251-L266

The white paper does not motivate why this is done. I would argue that the HMAC implementation of Rosenpass is not following [RFC 2104](https://datatracker.ietf.org/doc/html/rfc2104) as referenced in [^12].

Interestingly, also Jason Donenfeld is arguing that HMAC-Blake2s is not that useful?

https://lore.kernel.org/lkml/20220111181037.632969-2-Jason@zx2c4.com/

[^12]: Dr. Hugo Krawczyk, Mihir Bellare, and Ran Canetti. HMAC: Keyed-Hashing for
Message Authentication. RFC 2104. Feb. 1997. DOI: 10.17487/RFC2104. https:
//www.rfc-editor.org/info/rfc2104 (cit. on p. 4).

**Comment by stv0g** [comment]
## Figure 3 / Section 2.5: Wrong order of mixing in `en/decaps_and_mix()`

The white paper mixes in the following order:

1. pk
2. ct
3. shk

The Rust implementation mixes in the following:

1. pk
2. shk
3. ct

See: https://github.com/rosenpass/rosenpass/blob/b29720b0c67ddf96f114c134bed076f27018313e/src/protocol.rs#L1251-L1252

**Comment by stv0g** [comment]
### Wrong field ordering in RespHello message

The white paper defines the order as follows:

1. sidr
2. sidi
3. ecti
4. scti
5. biscuit
6. auth

The Rust code implements it as

1. sidr
2. sidi
3. ecti
4. scti
5. biscuit
6. auth

Note that 5. and 6. are swapped:

https://github.com/rosenpass/rosenpass/blob/b29720b0c67ddf96f114c134bed076f27018313e/src/msgs.rs#L265

**Comment by koraa** [comment]
> ### Section 2.1.1: Describe non-standard HMAC-Blake2 variant
> 
> I fallen into the trap to assume that the key of the inner Blake2 hash-function for the HMAC calculation will be set to zero like Wireguard is doing it:
> 
> https://github.com/WireGuard/wireguard-go/blob/052af4a8072bbbd3bfe7edf46fe3c1b350f71f08/device/noise-helpers.go#L24-L31
> 
> However, Rosenpass seems to take another approach and uses the `ipad`/`opad` xor-ed key (`temp_key` in the code) as the key for the inner hash functions:
> 
> https://github.com/rosenpass/rosenpass/blob/b29720b0c67ddf96f114c134bed076f27018313e/src/sodium.rs#L251-L266
> 
> The white paper does not motivate why this is done. I would argue that the HMAC implementation of Rosenpass is not following [RFC 2104](https://datatracker.ietf.org/doc/html/rfc2104) as referenced in [1](#user-content-fn-12-fb4d902f8b48d5eac583aa77e22018e2).
> 
> Interestingly, also Jason Donenfeld is arguing that HMAC-Blake2s is not that useful?
> 
> https://lore.kernel.org/lkml/20220111181037.632969-2-Jason@zx2c4.com/
> ## Footnotes
> 
>     1. Dr. Hugo Krawczyk, Mihir Bellare, and Ran Canetti. HMAC: Keyed-Hashing for
>        Message Authentication. RFC 2104. Feb. 1997. DOI: 10.17487/RFC2104. https:
>        //www.rfc-editor.org/info/rfc2104 (cit. on p. 4). [leftwards_arrow_with_hook](#user-content-fnref-12-fb4d902f8b48d5eac583aa77e22018e2)

The entire situation surrounding HMAC is a mess…I'll tell you some time in detail; it's better as an anecdote than as a technical comment. Right now the assumption is that rosenpass does the same thing WireGuard does; although I haven't consulted the WireGuard source code myself. I'll do a deep dive when I apply your comments to check this.

Good catch!

**Comment by stv0g** [comment]
Hi @koraa,

do you mind if I split up this issue into multipLe issues for addressing, discussing each individual inconsistency?
Or do you prefer to have it all in one?

**Comment by koraa** [comment]
> Hi @koraa,
> 
> do you mind if I split up this issue into multipLe issues for addressing, discussing each individual inconsistency? Or do you prefer to have it all in one?

I kind of like having it in one issue, I'd wait until this commit settles and then address all issues in one go xD.
We could also convert this into a project though.

**Comment by stv0g** [comment]
### Mismatching biscuit key epoch

The white paper says:

> The biscuit_key used to encrypt biscuits should be rotated every two minutes.

The Rust implementation uses an epoch of 5 minutes:

https://github.com/stv0g/rosenpass/blob/d204c4daa9f17f0853ce15b27e054a7cd30c112e/src/protocol.rs#L114

**Comment by stv0g** [comment]
### Figure 3: Indicate when responder/initiator are authenticated

I think Figure 3 would be a great place to show from which step onwards responder/initiators are authenticated. This is currently only visualized in Figure 1 in which we are lacking the implementation details.

**Comment by stv0g** [comment]
### Some nits from @wucke13 and @emilengler

From https://github.com/rosenpass/rosenpass/issues/108

> @wucke13 and I just went through the whitepaper together and found some slight issues, which are as follows:
> 
> * `s/private/secret/g`
> * `s/server/responder/g`
> * Renaming `pidiC` to `pidict` to imply its ciphertext nature
> * What do the results in the `Global Domain` diagram mean? Are they hash functions, are they hash inputs?
>     * Consider expanding the legend; explain what `>` and `>>` mean a bit further

**Comment by koraa** [comment]
@stv0g I applied most of your suggestions; I decided not to apply the rest of the suggestions or to do something else entirely (such as migrating to SHA3).

Further work is tracked in #136

**Comment by ilka-schulz** [comment]
It looks to me like this issue is basically done except the task of `Highlight relation to WireGuard whitepaper`. I went through the [current version of the Rosenpass whitepaper](https://rosenpass.eu/docs/rosenpass-project/whitepaper/) and It looks to me like this might also be resolved.

I am closing this issue for now and asking everyone involved to re-open it if I misread the situation.
